version: "3"

services:
  example-service:
    build: ./example-service
  nginx: 
    image: nginx:latest
    volumes:
      - ./ngnix-config/:/etc/nginx/conf.d
    ports:
      - 443:443
    depends_on:
      - example-service
